name: draggan_project
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.25
  - click>=8.0
  - pillow=9.4.0
  - scipy=1.11.1
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==2.0.0
    - glfw==2.6.1
    - gradio==3.39.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pytorch==2.0.1+cu118
    - torchvision
    - opencv-python
    - lpips
    - pyspng-seunglab
